#!/usr/bin/env sh
# install.sh — AURa OS one-command installer for Termux / Linux
#
# Usage (Termux/Android):
#   curl -fsSL https://raw.githubusercontent.com/Cbetts1/psychic-palm-tree/main/install.sh | sh
#
# Usage (local):
#   sh install.sh
#
# Environment overrides:
#   AURA_REPO_URL   — git clone URL  (default: GitHub HTTPS)
#   AURA_INSTALL_DIR — where to clone (default: ~/aura-os)
#   AURA_ROOT        — data root dir  (default: ~/.aura)
#
# POSIX-compliant; no root/sudo required; works in Termux on ARM64.
set -e

AURA_REPO_URL="${AURA_REPO_URL:-https://github.com/Cbetts1/psychic-palm-tree}"
AURA_INSTALL_DIR="${AURA_INSTALL_DIR:-${HOME}/aura-os}"
AURA_ROOT="${AURA_ROOT:-${HOME}/.aura}"

# ── Banner ────────────────────────────────────────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════════════╗"
echo "  ║     AURa OS — Installer                  ║"
echo "  ╚══════════════════════════════════════════╝"
echo ""

# ── Detect environment ────────────────────────────────────────────────────────
if [ -d "/data/data/com.termux" ]; then
    ENV_TYPE="termux"
else
    ENV_TYPE="linux"
fi

echo "  Environment : ${ENV_TYPE}"
echo "  Install dir : ${AURA_INSTALL_DIR}"
echo "  AURa root   : ${AURA_ROOT}"
echo ""

# ── Dependency helpers ────────────────────────────────────────────────────────
_need_cmd() {
    CMD="$1"
    PKG="$2"
    if command -v "${CMD}" >/dev/null 2>&1; then
        echo "  [OK] ${CMD}"
        return 0
    fi
    echo "  [..] Installing ${PKG}..."
    if [ "${ENV_TYPE}" = "termux" ]; then
        pkg install -y "${PKG}"
    else
        echo "  [!!] Please install '${PKG}' manually and re-run this script."
        exit 1
    fi
}

echo "  Checking dependencies..."
_need_cmd python3 python
_need_cmd git     git
echo ""

# ── Clone or update ───────────────────────────────────────────────────────────
if [ -d "${AURA_INSTALL_DIR}/.git" ]; then
    echo "  Updating existing installation in ${AURA_INSTALL_DIR}..."
    cd "${AURA_INSTALL_DIR}"
    git pull --ff-only
else
    echo "  Cloning AURa OS..."
    git clone "${AURA_REPO_URL}" "${AURA_INSTALL_DIR}"
    cd "${AURA_INSTALL_DIR}"
fi

# ── Create AURa filesystem ────────────────────────────────────────────────────
echo "  Creating AURa filesystem at ${AURA_ROOT}..."
mkdir -p "${AURA_ROOT}/local/cache/models"
mkdir -p "${AURA_ROOT}/local/packages"
mkdir -p "${AURA_ROOT}/cloud/images"
mkdir -p "${AURA_ROOT}/cloud/videos"
mkdir -p "${AURA_ROOT}/cloud/apk"
mkdir -p "${AURA_ROOT}/cloud/docs"
mkdir -p "${AURA_ROOT}/cloud/models"
mkdir -p "${AURA_ROOT}/cloud/index"
mkdir -p "${AURA_ROOT}/cloud/search"
mkdir -p "${AURA_ROOT}/cloud/manifests"
mkdir -p "${AURA_ROOT}/cloud/packages"

# ── Install launcher script ───────────────────────────────────────────────────
# On Termux, $PREFIX/bin is on $PATH.  On Linux, fall back to ~/.local/bin.
if [ -n "${PREFIX}" ]; then
    BIN_DIR="${PREFIX}/bin"
else
    BIN_DIR="${HOME}/.local/bin"
fi
mkdir -p "${BIN_DIR}"
LAUNCHER="${BIN_DIR}/aura"

echo "  Installing launcher → ${LAUNCHER}"
cat > "${LAUNCHER}" << LAUNCHEREOF
#!/usr/bin/env sh
# AURa OS launcher — generated by install.sh
set -e
AURA_INSTALL_DIR="${AURA_INSTALL_DIR}"
export PYTHONPATH="\${AURA_INSTALL_DIR}"
cd "\${AURA_INSTALL_DIR}"
exec python3 -m core.runtime.vhost "\$@"
LAUNCHEREOF
chmod +x "${LAUNCHER}"

# ── Install node-daemon helper ────────────────────────────────────────────────
NODE_DAEMON="${BIN_DIR}/aura-node"
cat > "${NODE_DAEMON}" << DAEMONEOF
#!/usr/bin/env sh
# Start AURa command channel in the background
set -e
AURA_INSTALL_DIR="${AURA_INSTALL_DIR}"
export PYTHONPATH="\${AURA_INSTALL_DIR}"
cd "\${AURA_INSTALL_DIR}"
exec sh tools/scripts/node_daemon.sh "\$@"
DAEMONEOF
chmod +x "${NODE_DAEMON}"

# ── Final message ─────────────────────────────────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════════════╗"
echo "  ║   AURa OS installation complete!         ║"
echo "  ╚══════════════════════════════════════════╝"
echo ""
echo "  Start operator console : aura"
echo "  Start node daemon      : aura-node start"
echo "  Health check           : aura-node health"
echo ""
echo "  AURa root  : ${AURA_ROOT}"
echo "  Install dir: ${AURA_INSTALL_DIR}"
echo ""
echo "  Tip: add ${BIN_DIR} to your PATH if not already present."
echo ""
