"""
builder.py — AURa OS module builder / code-generation engine.

Generates new worker modules, command handlers, and JSON config stubs
from built-in templates, then writes them into the correct repository
paths.  All generated files are fully functional — no placeholders.

Public API
----------
build_worker(name)        → cloud/workers/<slug>.py
build_command(name)       → core/shell/ext/<slug>.py
build_config_stub(name)   → ~/.aura/local/cache/<slug>.config.json
list_templates()          → list of available template descriptions
"""

import os
import re
import datetime

from core.runtime.paths import aura_path
from core.runtime.logs  import write_log


# ── Helpers ───────────────────────────────────────────────────────────────────

def _slugify(name):
    """Convert an arbitrary name to a safe Python identifier / slug."""
    s = re.sub(r"[^a-zA-Z0-9_]", "_", name.strip().lower())
    return re.sub(r"_+", "_", s).strip("_") or "module"


def _repo_root():
    """Resolve the absolute repo root (two levels above core/runtime/)."""
    return os.path.dirname(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    )


# ── Worker template ───────────────────────────────────────────────────────────

_WORKER_TEMPLATE = '''\
"""
{module_name}.py — AURa cloud worker: {display_name}

Generated by AURa Builder on {date}.
"""

import os
import uuid

from core.runtime.paths import aura_path
from core.runtime.logs  import write_log

_OUTPUT_DIR = aura_path("cloud", "{slug}")


def _ensure_dir():
    os.makedirs(_OUTPUT_DIR, exist_ok=True)


def run_{slug}_job(payload):
    """
    Execute a {display_name} job.

    Parameters
    ----------
    payload : dict
        Job parameters.  Expected keys (all optional):
          prompt  : str   — text prompt / input data
          options : dict  — extra processing options

    Returns
    -------
    dict with keys: type, output
    """
    _ensure_dir()

    prompt  = payload.get("prompt", "")  if isinstance(payload, dict) else str(payload)
    options = payload.get("options", {{}}) if isinstance(payload, dict) else {{}}

    # ── Job logic ──────────────────────────────────────────────────────────────
    # Replace this section with real processing logic.
    result_text = (
        f"{display_name} job output\\n"
        f"  prompt : {{prompt!r}}\\n"
        f"  options: {{options!r}}\\n"
    )

    out_file = os.path.join(_OUTPUT_DIR, f"{slug}_{{uuid.uuid4().hex[:8]}}.txt")
    with open(out_file, "w") as f:
        f.write(result_text)

    write_log(f"{display_name} job complete: {{out_file}}")
    return {{
        "type":   "{slug}",
        "prompt": prompt,
        "output": out_file,
    }}
'''


# ── Command template ──────────────────────────────────────────────────────────

_COMMAND_TEMPLATE = '''\
"""
{module_name}.py — AURa shell command: {display_name}

Generated by AURa Builder on {date}.
"""

from core.runtime.logs import write_log


def run_{slug}(args=None):
    """
    Execute the /{slug} shell command.

    Parameters
    ----------
    args : list[str] | None
        Tokenised command-line arguments (argv[1:]).

    Returns
    -------
    str — output displayed in the AURa shell.
    """
    args = args or []
    write_log(f"Command {slug} called with args={{args!r}}")

    if not args:
        return "Usage: {slug} <argument>"

    # ── Command logic ──────────────────────────────────────────────────────────
    # Replace this section with the real command implementation.
    return f"{display_name}: {{' '.join(args)}}"
'''


# ── Config stub template ──────────────────────────────────────────────────────

_CONFIG_TEMPLATE = '''\
{{
  "_comment": "{display_name} configuration — generated by AURa Builder on {date}",
  "enabled": true,
  "options": {{}}
}}
'''


# ── Public API ────────────────────────────────────────────────────────────────

def build_worker(name):
    """
    Generate a new cloud worker module.

    The new module is written to cloud/workers/<slug>.py and its import
    is appended to cloud/workers/__init__.py and core/runtime/worker_router.py.

    Returns
    -------
    dict with keys: status ("created" | "exists"), path, name
    """
    slug    = _slugify(name)
    display = slug.replace("_", " ").title()
    date    = datetime.datetime.now().strftime("%Y-%m-%d")
    root    = _repo_root()

    workers_dir = os.path.join(root, "cloud", "workers")
    os.makedirs(workers_dir, exist_ok=True)

    out_path = os.path.join(workers_dir, f"{slug}.py")
    if os.path.exists(out_path):
        return {"status": "exists", "path": out_path, "name": slug}

    content = _WORKER_TEMPLATE.format(
        module_name=slug,
        display_name=display,
        slug=slug,
        date=date,
    )
    with open(out_path, "w") as f:
        f.write(content)

    _register_worker_export(workers_dir, slug)
    write_log(f"Builder: worker created — {out_path}")
    return {"status": "created", "path": out_path, "name": slug}


def build_command(name):
    """
    Generate a new shell command handler.

    The new module is written to core/shell/ext/<slug>.py.

    Returns
    -------
    dict with keys: status ("created" | "exists"), path, name
    """
    slug    = _slugify(name)
    display = slug.replace("_", " ").title()
    date    = datetime.datetime.now().strftime("%Y-%m-%d")
    root    = _repo_root()

    cmds_dir  = os.path.join(root, "core", "shell", "ext")
    os.makedirs(cmds_dir, exist_ok=True)

    init_path = os.path.join(cmds_dir, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, "w") as f:
            f.write("")

    out_path = os.path.join(cmds_dir, f"{slug}.py")
    if os.path.exists(out_path):
        return {"status": "exists", "path": out_path, "name": slug}

    content = _COMMAND_TEMPLATE.format(
        module_name=slug,
        display_name=display,
        slug=slug,
        date=date,
    )
    with open(out_path, "w") as f:
        f.write(content)

    write_log(f"Builder: command created — {out_path}")
    return {"status": "created", "path": out_path, "name": slug}


def build_config_stub(name):
    """
    Generate a JSON config stub inside the AURa cache directory.

    Returns
    -------
    dict with keys: status ("created" | "exists"), path, name
    """
    slug    = _slugify(name)
    display = slug.replace("_", " ").title()
    date    = datetime.datetime.now().strftime("%Y-%m-%d")

    cfg_path = aura_path("local", "cache", f"{slug}.config.json")
    if os.path.exists(cfg_path):
        return {"status": "exists", "path": cfg_path, "name": slug}

    content = _CONFIG_TEMPLATE.format(display_name=display, date=date)
    with open(cfg_path, "w") as f:
        f.write(content)

    write_log(f"Builder: config stub created — {cfg_path}")
    return {"status": "created", "path": cfg_path, "name": slug}


def list_templates():
    """Return list of dicts describing available build templates."""
    return [
        {
            "name":        "worker",
            "description": "Cloud worker module — cloud/workers/<name>.py",
            "entrypoint":  "run_<name>_job(payload)",
        },
        {
            "name":        "command",
            "description": "Shell command handler — core/shell/ext/<name>.py",
            "entrypoint":  "run_<name>(args)",
        },
        {
            "name":        "config",
            "description": "JSON config stub — ~/.aura/local/cache/<name>.config.json",
            "entrypoint":  "N/A",
        },
    ]


# ── Internal helpers ──────────────────────────────────────────────────────────

def _register_worker_export(workers_dir, slug):
    """
    Append the new worker's import line to cloud/workers/__init__.py.
    Then attempt to add the mapping to worker_router.py.
    """
    init_path   = os.path.join(workers_dir, "__init__.py")
    import_line = f"from cloud.workers.{slug} import run_{slug}_job"

    if not os.path.exists(init_path):
        with open(init_path, "w") as f:
            f.write("")

    with open(init_path, "r") as f:
        current = f.read()

    if import_line not in current:
        with open(init_path, "a") as f:
            f.write(f"\n{import_line}\n")

    _register_router_entry(slug)


def _register_router_entry(slug):
    """
    Append the new worker to core/runtime/worker_router.py's _WORKER_MAP
    if it is not already present.
    """
    root        = _repo_root()
    router_path = os.path.join(root, "core", "runtime", "worker_router.py")
    if not os.path.exists(router_path):
        return

    with open(router_path, "r") as f:
        src = f.read()

    import_line = f"from cloud.workers.{slug} import run_{slug}_job"
    if import_line in src:
        return  # already registered

    map_entry = f'    "{slug}":  run_{slug}_job,'
    if map_entry in src:
        return

    # Insert import before _WORKER_MAP definition
    src = src.replace(
        "\n_WORKER_MAP = {",
        f"\n{import_line}\n\n_WORKER_MAP = {{",
        1,
    )
    # Insert map entry before the closing brace of _WORKER_MAP
    src = src.replace(
        "\n}\n\n\ndef route_worker",
        f"\n    {map_entry}\n}}\n\n\ndef route_worker",
        1,
    )
    with open(router_path, "w") as f:
        f.write(src)
